<a href="https://colab.research.google.com/github/nurkausarmuner-enka/dl-assignment-01-numpy-neural-network/blob/main/A_numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Muner Nurkaussar
# A.1 Matrix Multiplication (Resource Allocation)
import numpy as np

In [17]:
Resources_Matrix = np.array([
    [15, 20],   # Team 1
    [10, 25],   # Team 2
    [15, 30]    # Team 3
])

Allocation_Factors = np.array([
    [0.8, 1.2],
    [1.0, 0.5]
])

print(Resources_Matrix.shape)
print(Allocation_Factors.shape)

(3, 2)
(2, 2)


In [18]:
a = np.dot(Resources_Matrix, Allocation_Factors)
print('output:')
print(a)

output:
[[32.  28. ]
 [33.  24.5]
 [42.  33. ]]


In [20]:
# A.2 Element-wise Operations (Production Tracking)
Shift_A_Production = np.array([
    [10, 12, 11, 13, 14, 15, 16],  # Factory 1
    [8,  9,  10, 11, 12, 13, 14],  # Factory 2
    [15, 14, 13, 12, 11, 10, 9]    # Factory 3
])

Shift_B_Production = np.array([
    [5,  6,  5,  6,  7,  6,  5],   # Factory 1
    [4,  5,  4,  5,  6,  5,  4],   # Factory 2
    [6,  5,  6,  5,  4,  5,  6]    # Factory 3
])
print(Shift_A_Production.shape)
print(Shift_B_Production.shape)

(3, 7)
(3, 7)


In [21]:
Total_Production = Shift_A_Production + Shift_B_Production
print(Total_Production)

[[15 18 16 19 21 21 21]
 [12 14 14 16 18 18 18]
 [21 19 19 17 15 15 15]]


In [23]:
# A.3 Activation Function (Sigmoid in Sales Forecasting)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [24]:
forecast_values = np.array([-2, -1, 0, 1, 2])
sigmoid_output = sigmoid(forecast_values)

print("Forecast values:")
print(forecast_values)

print("Sigmoid output:")
print(sigmoid_output)

Forecast values:
[-2 -1  0  1  2]
Sigmoid output:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [25]:
# A.4 Gradient Calculation (Learning Adjustment)
def sigmoid_gradient(x):
    s = sigmoid(x)
    return s * (1 - s)

In [26]:
gradient_output = sigmoid_gradient(forecast_values)

print("Forecast values:")
print(forecast_values)

print("Sigmoid gradient:")
print(gradient_output)

Forecast values:
[-2 -1  0  1  2]
Sigmoid gradient:
[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
